// flow-typed signature: b26dfccb7494fdb0075f1bba40946192
// flow-typed version: <<STUB>>/eslint-config-standard-preact_v^1.1.6/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-standard-preact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-standard-preact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-standard-preact/test/basic' {
  declare module.exports: any;
}

declare module 'eslint-config-standard-preact/test/validate-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-standard-preact/index' {
  declare module.exports: $Exports<'eslint-config-standard-preact'>;
}
declare module 'eslint-config-standard-preact/index.js' {
  declare module.exports: $Exports<'eslint-config-standard-preact'>;
}
declare module 'eslint-config-standard-preact/test/basic.js' {
  declare module.exports: $Exports<'eslint-config-standard-preact/test/basic'>;
}
declare module 'eslint-config-standard-preact/test/validate-config.js' {
  declare module.exports: $Exports<'eslint-config-standard-preact/test/validate-config'>;
}
